# Generated by Django 5.0.1 on 2024-02-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramImageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='telegram_images_orders/')),
            ],
            options={
                'verbose_name': 'Изображение для отображения в заказе',
                'verbose_name_plural': 'Изображения для отображения в заказе',
            },
        ),
    ]
