# Generated by Django 5.0.1 on 2024-02-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_telegramimageorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramimageorder',
            name='order_status',
            field=models.IntegerField(default=1, max_length=1, unique=True, verbose_name='Статус заказа'),
            preserve_default=False,
        ),
    ]
