# Generated by Django 5.0.1 on 2024-02-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_alter_telegramimageorder_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramimageorder',
            name='order_status',
            field=models.CharField(choices=[('1', 'Не готов'), ('2', 'Готов к выдаче'), ('3', 'Передан в доставку'), ('4', 'Доставлен'), ('5', 'Отменен'), ('6', 'Завершен')], max_length=1, unique=True, verbose_name='Статус заказа'),
        ),
    ]
