# Generated by Django 5.0.1 on 2024-03-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0002_sertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertificate',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
