# Generated by Django 5.0.1 on 2024-03-16 09:19

import sitedb.Utils.Code.Sertificate.sertificate_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0003_sertificate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertificate',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='code',
            field=models.CharField(default=sitedb.Utils.Code.Sertificate.sertificate_generator.generate_certificate_code, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
