# Generated by Django 5.0.1 on 2024-03-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0004_sertificate_text_alter_sertificate_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertificate',
            name='discount',
            field=models.IntegerField(default=10, verbose_name='Скидка %'),
        ),
    ]
