# Generated by Django 5.0.1 on 2024-04-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0004_siteimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurWorkImage',
        ),
        migrations.AlterField(
            model_name='ourwork',
            name='image',
            field=models.ManyToManyField(to='sitedb.siteimage', verbose_name='Картинки нашей работы'),
        ),
    ]
