# Generated by Django 5.0.1 on 2024-04-08 13:54

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0005_delete_ourworkimage_alter_ourwork_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='service',
            name='slider',
            field=models.ManyToManyField(blank=True, to='sitedb.siteimage', verbose_name='Слайдер'),
        ),
        migrations.AddField(
            model_name='service',
            name='table',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Таблица'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='service/', verbose_name='Картинка'),
        ),
    ]
