# Generated by Django 5.0.1 on 2024-03-16 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0005_sertificate_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertificate',
            name='discount',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Скидка %'),
        ),
    ]
