# Generated by Django 5.0.1 on 2024-04-08 14:03

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0006_rename_title_service_name_service_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterField(
            model_name='service',
            name='table',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Текст который будет отображен внизу страницы', verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Текст который будет отображен в начале странице', verbose_name='Текст'),
        ),
    ]
