# Generated by Django 5.0.1 on 2024-03-16 09:48

import django.core.validators
import sitedb.Utils.Code.Sertificate.sertificate_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0006_alter_sertificate_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertificate',
            name='code',
            field=models.CharField(default=sitedb.Utils.Code.Sertificate.sertificate_generator.generate_certificate_code, max_length=20, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='discount',
            field=models.IntegerField(default=10, help_text='Размер скидки в процентах', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='quanity',
            field=models.IntegerField(default=0, verbose_name='Количество использованний'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='text',
            field=models.TextField(help_text='Текст сертификата, который будет отправлен на почту пользователя', verbose_name='Текст'),
        ),
    ]
