# Generated by Django 5.0.1 on 2024-03-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitedb", "0007_alter_sertificate_code_alter_sertificate_discount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ourworkimage",
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.RemoveField(
            model_name="sertificate",
            name="text",
        ),
        migrations.AddField(
            model_name="sertificate",
            name="personal",
            field=models.BooleanField(
                default=False,
                help_text="Сертификат не будет отправлен всем пользователям, которые подписались на рассылку",
                verbose_name="Персональный",
            ),
        ),
        migrations.AlterField(
            model_name="sertificate",
            name="code",
            field=models.CharField(
                default="FiCb-roUb-JZFh-CQjc",
                max_length=20,
                unique=True,
                verbose_name="Код",
            ),
        ),
    ]
