# Generated by Django 5.0.1 on 2024-03-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0008_alter_ourworkimage_options_remove_sertificate_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertificate',
            name='code',
            field=models.CharField(default='pnYP-jbiD-h4f5-YRpN', max_length=20, unique=True, verbose_name='Код'),
        ),
    ]
