# Generated by Django 5.0.1 on 2024-04-09 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0009_remove_service_url_service_our_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='our_work',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slider',
        ),
        migrations.AlterField(
            model_name='service',
            name='our_work_is_active',
            field=models.BooleanField(default=True, verbose_name='Отоброжать наши работы'),
        ),
        migrations.CreateModel(
            name='ServiceOurWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.ourwork')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.service')),
            ],
            options={
                'verbose_name': 'Наша работа',
                'verbose_name_plural': 'Наши работы',
            },
        ),
        migrations.CreateModel(
            name='ServiceSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.service')),
                ('site_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.siteimage')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
