# Generated by Django 5.0.1 on 2024-03-26 05:14

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0009_alter_sertificate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='code',
            field=models.CharField(default='cVwZ-7dAd-9ldk-ksDc', max_length=20, unique=True, verbose_name='Код'),
        ),
    ]
