# Generated by Django 5.0.1 on 2024-03-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0010_slider_text_alter_sertificate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertificate',
            name='code',
            field=models.CharField(default='59wp-0VNp-1DGA-SMdS', max_length=20, unique=True, verbose_name='Код'),
        ),
    ]
