# Generated by Django 5.0.1 on 2024-03-27 05:17

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0011_alter_sertificate_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='url',
        ),
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='code',
            field=models.CharField(default='iG98-00E6-oBjW-1jtW', max_length=20, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(default=django.utils.timezone.now, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
