# Generated by Django 5.0.1 on 2024-04-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0011_alter_serviceourwork_our_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='url',
            field=models.URLField(default=1, max_length=255, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='our_work_is_active',
            field=models.BooleanField(default=False, verbose_name='Отоброжать наши работы'),
        ),
    ]
