# Generated by Django 5.0.1 on 2024-04-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0012_slider_url_alter_service_our_work_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ответ предоствлен')),
            ],
            options={
                'verbose_name': 'Фидбэк',
                'verbose_name_plural': 'Фидбэк',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
