# Generated by Django 5.0.1 on 2024-04-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0013_feedback_vacancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
