# Generated by Django 5.0.1 on 2024-04-22 07:44

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0017_address_requisites_wokrtime_remove_contact_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='table',
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Текст который будет отображен на странице', verbose_name='Текст'),
        ),
    ]
