# Generated by Django 5.0.1 on 2024-04-22 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0019_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Информация о сайте',
                'verbose_name_plural': 'Информация о сайте',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitedb.siteinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitedb.siteinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitedb.siteinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wokrtime',
            name='info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitedb.siteinfo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
