# Generated by Django 5.0.1 on 2024-04-22 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0020_siteinfo_address_info_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitedb.siteinfo'),
            preserve_default=False,
        ),
    ]
