# Generated by Django 5.0.1 on 2024-04-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0021_requisites_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
