version: '3.9'
services:
  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py create_data && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 1"
    volumes:
      - ./backend:/backend
      - static:/backend/staticfiles
      - media:/backend/media
    env_file:
      - backend/.env
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  redis:
    image: redis:latest
    container_name: redis01

  celery:
    build: ./backend
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/backend
    env_file:
      - backend/.env
    depends_on:
      - redis
      - backend

  celery-beat:
    build: ./backend
    command: celery -A backend beat -l info
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend:/backend
