version: '3.9'
services:
  backend:
    build: ./backend
    volumes:
      - .:/backend
    env_file:
      - backend/.env
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend

  redis:
    image: redis:latest
    container_name: redis01

  celery:
    build: ./backend
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/backend
    env_file:
      - backend/.env
    depends_on:
      - redis
      - backend

  celery-beat:
    build: ./backend
    command: celery -A backend beat -l info
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend:/backend
