version: '3.9'

services:
  backend:
    build: .
    command: bash -c "python manage.py migrate && python manage.py create_data && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:8080 --workers 1"
    ports:
      - 8080:8080

  celery:
    build: .
    restart: always
    command: celery -A backend worker -l info
    depends_on:
      - backend
      - redis
  celery-beat:
    build: .
    restart: always
    command: celery -A backend beat -l info
    depends_on:
      - backend
      - redis

  redis:
    image: redis:latest
