version: '3.9'
services:

  main:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - /.env
    volumes:
      - .:/db
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis:latest

  celery:
    restart: always
    build:
      context: .
    command: celery -A backend worker -l info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/backend
    env_file:
      - /.env
    depends_on:
      - main
      - redis

  telegram_bot:
    build:
      context: .
    command: python manage.py bot
    depends_on:
      - main
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_DB: Antur
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7089010POUTose
