"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import datetime

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition1

INSTALLED_APPS = [
    "jazzmin.apps.JazzminConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "sitedb.apps.SitedbConfig",  # Site Info etc
    "users.apps.UsersConfig",  # AUTH USER API
    "profiles.apps.ProfilesConfig",  # User Profiles API
    "telegram.apps.TelegramConfig",  # Integrate TG BOT
    "DB.apps.DbConfig",  # Database
    "order.apps.OrderConfig",  # Order API
    "API.apps.ApiConfig",  # Product API
    "reviews.apps.ReviewsConfig",  # Reviews API
    "django_filters",  # Filters
    "colorfield",  # color field
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_swagger",  # swagger and docs
    "drf_yasg",
    "smsru",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
            os.path.join(BASE_DIR, "users/templates"),
            os.path.join(BASE_DIR, "DB/templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


"""
БАЗА ДАННЫХ
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT"),
    }
}
"""
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "RU-ru"

TIME_ZONE = "Asia/Yekaterinburg"

USE_I18N = True

USE_TZ = True


"""
STATIC SETTINGS
"""
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


"""
MEDIA SETTINGS
"""
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


"""
SITE_ID 
"""
SITE_ID = 1


"""
REST FRAMEWORK
"""
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}


"""
JWT TOKEN
"""
JWT_AUTH = {
    "JWT_EXPIRATION_DELTA": datetime.timedelta(
        hours=5
    ),  # Срок действия Access Token на 5 часов
    "JWT_REFRESH_EXPIRATION_DELTA": datetime.timedelta(
        days=7
    ),  # Срок действия Refresh Token на 7 дней
    "JWT_ALLOW_REFRESH": True,  # Разрешить обновление токена
}


"""
CUSTOM MODEL USER
"""
AUTH_USER_MODEL = "users.CustomUser"


"""
LOGGING
"""
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "file_format": {
            "format": "[%(asctime)s] %(levelname)s|%(module)s: %(message)s",
            "datefmt": "%d.%m.%Y %H:%M:%S",
        },
        "error_format": {
            "format": "[%(asctime)s - %(levelname)s] %(message)s, PATH: %(pathname)s, line: %(lineno)d",
            "datefmt": "%d.%m.%Y %H:%M:%S",
        },
        "security_error": {
            "format": "[%(asctime)s] - [%(levelname)s] - [%(module)s] - %(message)s",
            "datefmt": "%d/%m/%Y %H:%M:%S",
        },
    },
    "handlers": {
        "errors": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/errors.log"),
            "maxBytes": 1024 * 1024 * 5,
            "backupCount": 5,
            "formatter": "error_format",
            "level": "ERROR",
        },
        "security": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/security.log"),
            "maxBytes": 1024 * 1024 * 5,
            "backupCount": 5,
            "formatter": "security_error",
            "level": "INFO",
        },
        "telegram_bot": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/telegram_bot.log"),
            "maxBytes": 1024 * 1024 * 5,
            "backupCount": 5,
            "formatter": "error_format",
            "level": "ERROR",
        },
        "payment_create": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/payment_create.log"),
            "maxBytes": 1024 * 1024 * 5,
            "backupCount": 5,
            "formatter": "error_format",
            "level": "ERROR",
        },
    },
    "loggers": {
        "django.request": {"handlers": ["errors"], "level": "ERROR", "propagate": True},
        "django.security": {
            "handlers": ["security"],
            "level": "INFO",
            "propagate": True,
        },
        "tg_bot": {
            "handlers": ["telegram_bot"],
            "level": "ERROR",
            "propagate": True,
        },
        "payment_create": {
            "handlers": ["payment_create"],
            "level": "ERROR",
            "propagate": True,
        },
    },
}


"""
MAIL SETTINGS
"""
# if DEBUG:
#     EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# else:
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.yandex.ru"
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


"""
REDIS SETTINGS
"""
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
REDIS_DB = os.getenv("REDIS_DB")


"""
CELERY SETTINGS
"""
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


"""
SMS SETTINGS
"""
SMS_RU = {
    "API_ID": os.getenv("SMS_RU_API_ID"),
    "FROM": os.getenv("SMSRU_FROM"),
}


"""
Yookassa
"""
YOOKASSA_ACCOUNT_ID = os.getenv("YOOKASSA_ACCOUNT_ID")
YOOKASSA_SECRET = os.getenv("YOOKASSA_SECRET")

# ADMIN SETTINGS
JAZZMIN_SETTINGS = {
    # Настройка сайта
    "site_title": "Антураж",
    "site_header": "Антураж",
    "welcome_sign": "Добро пожаловать в Антураж",
    "copyright": "Антураж",
    "site_logo_classes": "img-center",
    # Панель управления
    # моадльное окно
    "related_modal_active": True,
    # Панель кастомизации(только на время разработки)
    "show_ui_builder": True,
    # гугл шрифты
    "use_google_fonts_cdn": True,
    # Навигация(sidebar)
    "navigation_expanded": True,
    # Models icons
    "icons": {
        "auth": "fas fa-users-cog",
        "users.CustomUser": "fas fa-users",
        "auth.Group": "fas fa-users",
        "DB.Product": "fas fa-vest",
        "DB.Catalog": "fas fa-list-ul",
        "DB.Tags": "fas fa-tags",
        "DB.Color": "fas fa-palette",
        "DB.Size": "fas fa-ruler",
        "DB.ProductImage": "fas fa-image",
        "order.Order": "fas fa-truck",
        "order.Additionalservices": "fas fa-plus",
        "reviews.Review": "fas fa-comment",
        "sitedb.Slider": "fas fa-sliders-h",
        "sitedb.News": "fas fa-newspaper",
        "sitedb.Service": "fas fa-list",
        "sitedb.OurWork": "fas fa-briefcase",
        "sitedb.OurWorkImage": "fas fa-image",
        "telegram.TelegramImage": "fas fa-image",
        "telegram.TelegramNews": "fas fa-paper-plane",
        "smsru.Log": "fas fa-sms",
    },
    # TOP MENU
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "Главная", "url": "admin:index", "permissions": ["auth.view_user"]},
        # external url that opens in a new window (Permissions can be added)
        {
            "name": "Поддержка(DEV)",
            "url": "admin:index",
            "new_window": False,
        },
        {"name": "books"},
        # model admin to link to (Permissions checked against model)
        # {"model": "order.Order"}, вывод конкретной модели
        # App with dropdown menu to all its models pages (Permissions checked against models)
        # {"app": "DB"}, вывод полного списка моделей приложения
    ],
    # FORMS
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    # SIDE BAR LIST MODELS AND APP
    "order_with_respect_to": [
        "DB",
        "DB.Product",
        "DB.Catalog",
        "DB.SubCatalog",
        "DB.Tags",
        "DB.Color",
        "DB.Size",
        "DB.ProductImage",
        "Support",
        "order",
        "order.Order",
        "sitedb",
        "sitedb.Slider",
        "sitedb.News",
        "sitedb.Service",
        "sitedb.OurWork",
        "telegram",
        "telegram.TelegramNews",
    ],
    "custom_links": {
        "books": [
            {
                # Any Name you like
                "name": "Тест",
                # url name e.g `admin:index`, relative urls e.g `/admin/index` or absolute urls e.g `https://domain.com/admin/index`
                "url": "admin:index",
                # any font-awesome icon, see list here https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2 (optional)
                "icon": "fas fa-comments",
                # a list of permissions the user must have to see this link (optional)
            }
        ]
    },
    #
    # Скрыть модели
    "hide_apps": ["auth", "AuthToken"],
    "hide_models": ["auth.groups", "auth.tokens.Tokens", "DB.Type"],
    # "language_chooser": True,
    "search_model": ["DB.Product"],
}
# UI ADMIN
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": False,
    "theme": "pulse",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
