# Generated by Django 5.0.1 on 2024-03-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_register',
        ),
    ]
