# Generated by Django 5.0.1 on 2024-03-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('1', 'Онланй платеж'), ('2', 'При получении')], default='1', max_length=1, verbose_name='Статус оплаты'),
        ),
    ]
