# Generated by Django 5.0.1 on 2024-04-04 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=255, verbose_name='ОГРН')),
                ('kpp', models.CharField(max_length=255, verbose_name='КПП')),
                ('bik', models.CharField(max_length=255, verbose_name='БИК')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('cores_account', models.CharField(blank=True, max_length=255, verbose_name='Корреспондентский счет')),
                ('ras_check', models.CharField(blank=True, max_length=255, verbose_name='Расчётный счет')),
                ('legal_address', models.CharField(blank=True, max_length=255, verbose_name='Юридический адрес')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='номер заказа')),
            ],
            options={
                'verbose_name': 'Юридические данные',
                'verbose_name_plural': 'Юридические данные',
            },
        ),
    ]
