# Generated by Django 5.0.1 on 2024-02-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='color',
            field=models.CharField(default=1, max_length=3, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitems',
            name='cost',
            field=models.FloatField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitems',
            name='size',
            field=models.CharField(default=1, max_length=3, verbose_name='Размер'),
            preserve_default=False,
        ),
    ]
