# Generated by Django 5.0.1 on 2024-03-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_status',
            new_name='payment_type',
        ),
    ]
