# Generated by Django 5.0.1 on 2024-04-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_legaldate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID платежа в Юкассе'),
        ),
        migrations.AlterField(
            model_name='legaldate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название Юр. лица'),
        ),
        migrations.AlterField(
            model_name='legaldate',
            name='ogrn',
            field=models.CharField(max_length=255, verbose_name='ОГРН/ЕГРП'),
        ),
    ]
