# Generated by Django 5.0.1 on 2024-03-16 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_user_register'),
        ('sitedb', '0007_alter_sertificate_code_alter_sertificate_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sertificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitedb.sertificate', verbose_name='Сертификат'),
        ),
    ]
