# Generated by Django 5.0.1 on 2024-02-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitems_product_alter_orderitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='total_cost',
            field=models.FloatField(default=1, verbose_name='Общая цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='color',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='size',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Размер'),
        ),
    ]
