# Generated by Django 5.0.1 on 2024-02-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitems_total_cost_alter_orderitems_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='total_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая цена'),
        ),
    ]
