# Generated by Django 5.0.1 on 2024-02-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderitems_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalservices',
            old_name='price',
            new_name='cost',
        ),
    ]
