# Generated by Django 5.0.1 on 2024-04-25 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0008_product_total_sales'),
        ('order', '0008_alter_orderaddress_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='DB.productinfo', verbose_name='Товар'),
        ),
    ]
