# Generated by Django 5.0.1 on 2024-02-19 09:05

import database.utils.order_number_generator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additionalservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название доп.услуги')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Доп.услуга',
                'verbose_name_plural': 'Доп.услуги',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название каталога')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog_images/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='Картинки товаров')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тэга')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_initials', models.CharField(max_length=100, verbose_name='Инициалы покупателя')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('user_phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('products', models.JSONField(verbose_name='Товары')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сформирован')),
                ('order_number', models.CharField(default=database.utils.order_number_generator.generate_order_number, max_length=10, unique=True, verbose_name='Номер заказа')),
                ('order_type', models.CharField(choices=[('1', 'Самовывоз'), ('2', 'Доставка до двери'), ('3', 'Доставка транспортной компанией')], default='1', max_length=1, verbose_name='Тип доставки')),
                ('order_paymant', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('order_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес доставки')),
                ('order_face', models.CharField(choices=[('1', 'Юридическое лицо'), ('2', 'Физическое лицо')], default='1', max_length=1, verbose_name='Тип лица')),
                ('order_status', models.CharField(choices=[('1', 'Не готов'), ('2', 'Готов к выдаче'), ('3', 'Передан в доставку'), ('4', 'Доставлен'), ('5', 'Отменен'), ('6', 'Завершен')], default='1', max_length=1, verbose_name='Статус')),
                ('track_number', models.CharField(blank=True, max_length=255, verbose_name='Номер отслеживания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарии')),
                ('order_additionalservices', models.ManyToManyField(blank=True, to='database.additionalservices', verbose_name='Доп.услуги')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='SubCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подкаталога')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcatalog_images')),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.catalog', verbose_name='Каталог')),
            ],
            options={
                'verbose_name': 'Подкаталог',
                'verbose_name_plural': 'Подкаталоги',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('cost', models.FloatField(verbose_name='Цена')),
                ('count', models.IntegerField(default=0, verbose_name='На складе')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('promotion', models.BooleanField(default=False, verbose_name='Товар по акции')),
                ('promotion_cost', models.FloatField(blank=True, null=True, verbose_name='Цена с учетом акции')),
                ('image', models.ManyToManyField(blank=True, to='database.productimage', verbose_name='Изображение')),
                ('size', models.ManyToManyField(to='database.size', verbose_name='Размеры')),
                ('subcatalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.subcatalog', verbose_name='Категория')),
                ('tags', models.ManyToManyField(to='database.tags', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
