# Generated by Django 5.0.1 on 2024-02-17 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcatalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.subcatalog', verbose_name='Категория'),
        ),
    ]
