# Generated by Django 5.0.1 on 2024-02-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='value',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
