# Generated by Django 5.0.1 on 2024-02-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_product_subcatalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='user_info',
            field=models.CharField(default=1, max_length=255, verbose_name='Информация о покупателе'),
            preserve_default=False,
        ),
    ]
