# Generated by Django 5.0.1 on 2024-02-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_order_user_email_alter_order_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
