# Generated by Django 5.0.1 on 2024-02-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_order_user_email_alter_order_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='database.product', verbose_name='Товары'),
        ),
    ]
