# Generated by Django 5.0.1 on 2024-02-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='database.product'),
        ),
    ]
