# Generated by Django 5.0.1 on 2024-02-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_cart_favorite_unique_favorite_cart_product_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
    ]
