# Generated by Django 5.0.1 on 2024-02-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_cart_is_ordered_remove_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
