# Generated by Django 5.0.1 on 2024-02-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
