# Generated by Django 5.0.1 on 2024-02-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_adress',
            new_name='order_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('1', 'Самовывоз'), ('2', 'Доставка')], default='1', max_length=1),
        ),
    ]
