# Generated by Django 5.0.1 on 2024-02-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_orderitems_options_alter_orderitems_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_register',
            field=models.BooleanField(default=False, verbose_name='Зарегистрирован'),
        ),
        migrations.DeleteModel(
            name='UsersOrder',
        ),
    ]
