# Generated by Django 5.0.1 on 2024-02-24 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталоги'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': 'Информация о продукте', 'verbose_name_plural': 'Информация о продуктах'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterModelOptions(
            name='subcatalog',
            options={'verbose_name': 'Подкаталог', 'verbose_name_plural': 'Подкаталоги'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Картинки товаров'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.size', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='subcatalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcatalog_images/'),
        ),
    ]
