# Generated by Django 5.0.1 on 2024-03-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(default=1, max_length=20, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
