# Generated by Django 5.0.1 on 2024-02-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_alter_catalog_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='count',
            new_name='quantity',
        ),
    ]
