# Generated by Django 5.0.1 on 2024-04-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_alter_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Состав')),
                ('ratio', models.FloatField(max_length=3, verbose_name='Доля (%)')),
            ],
            options={
                'verbose_name': 'Состав',
                'verbose_name_plural': 'Составы',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='compound',
            field=models.ManyToManyField(blank=True, help_text='Состав', to='DB.compound', verbose_name='Состав'),
        ),
    ]
