# Generated by Django 5.0.1 on 2024-03-26 08:39

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_alter_product_image_alter_product_sub_catalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0, help_text='Рейтинг товара, заполняется автоматически', verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Тэги', to='DB.tags', verbose_name='Тэги'),
        ),
    ]
