# Generated by Django 5.0.1 on 2024-04-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_compound_product_compound'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaundRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='compound',
            name='ratio',
        ),
        migrations.AddField(
            model_name='compound',
            name='ratio',
            field=models.ManyToManyField(to='DB.compaundratio', verbose_name='Соотношения'),
        ),
    ]
