# Generated by Django 5.0.1 on 2024-04-21 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0006_remove_compound_ratio_alter_compound_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='compound',
            table_comment='Question answers',
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0, help_text='Рейтинг товара, заполняется автоматически', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
    ]
