# Generated by Django 5.0.1 on 2024-04-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0007_alter_compound_table_comment_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sales',
            field=models.IntegerField(default=0, verbose_name='Количество продаж'),
        ),
    ]
