# Generated by Django 5.0.1 on 2024-05-01 15:20

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0008_product_total_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тестовый цвет',
                'verbose_name_plural': 'Тестовые цвета',
            },
        ),
        migrations.CreateModel(
            name='TestSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Тестовый размер',
                'verbose_name_plural': 'Тестовые размеры',
            },
        ),
        migrations.CreateModel(
            name='TestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='test_product_images/', verbose_name='Картинка')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
                ('attrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.testcolor', verbose_name='Цвет')),
                ('tags', models.ManyToManyField(blank=True, help_text='Тэги', to='DB.tags', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Тестовый продукт',
                'verbose_name_plural': 'Тестовые продукты',
            },
        ),
        migrations.AddField(
            model_name='testcolor',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.testsize', verbose_name='Размер'),
        ),
    ]
