# Generated by Django 5.0.1 on 2024-05-01 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0009_testcolor_testsize_testproduct_testcolor_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testproduct',
            name='attrs',
        ),
        migrations.CreateModel(
            name='TestProductColorSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.testcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.testproduct')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.testsize')),
            ],
            options={
                'verbose_name': 'Размер и цвет продукта',
                'verbose_name_plural': 'Размеры и цвета продукта',
            },
        ),
        migrations.AddField(
            model_name='testproduct',
            name='colors',
            field=models.ManyToManyField(through='DB.TestProductColorSize', to='DB.testcolor'),
        ),
    ]
