# Generated by Django 5.0.1 on 2024-05-02 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0010_remove_testproduct_attrs_testproductcolorsize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testproduct',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='testproductcolorsize',
            name='color',
        ),
        migrations.RemoveField(
            model_name='testproduct',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='testproductcolorsize',
            name='product',
        ),
        migrations.RemoveField(
            model_name='testproductcolorsize',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, help_text='цвета', to='DB.color', verbose_name='Цвета'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.type', verbose_name='Тип'),
        ),
        migrations.DeleteModel(
            name='TestColor',
        ),
        migrations.DeleteModel(
            name='TestProduct',
        ),
        migrations.DeleteModel(
            name='TestProductColorSize',
        ),
        migrations.DeleteModel(
            name='TestSize',
        ),
    ]
