# Generated by Django 5.0.1 on 2024-05-02 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0011_remove_testproduct_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='DB.product', verbose_name='Товар'),
        ),
    ]
