# Generated by Django 5.0.1 on 2024-04-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансию', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.RemoveField(
            model_name='responsevacancy',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_time',
            field=models.CharField(default=1, max_length=100, verbose_name='График работы'),
            preserve_default=False,
        ),
    ]
