# Generated by Django 5.0.1 on 2024-04-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_vacancy_salary_alter_responsevacancy_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsevacancy',
            name='user',
        ),
    ]
