# Generated by Django 5.0.1 on 2024-03-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_tg_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID в Телеграм'),
        ),
    ]
