# Generated by Django 5.0.1 on 2024-02-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verify_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
