# Generated by Django 5.0.1 on 2024-02-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_verify_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verify_code',
        ),
    ]
